### ISSUE TITLE
Say what's the deal? These packages are conflicting

### ISSUE THREAD

**Issue by MackNcD** [Vali-98/XTTS-RVC-UI#2]
Removed the specific versionings, and still managed to get this error:

      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      cl : Command line warning D9002 : ignoring unknown option '-O3'
      libbleu.cpp
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include\yvals.h(20): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

Can you explain why the numpy requirements are conflicting?
And why this won't work out of the gate?
What have you tested it on?
Do you have a YouTube video of your install methodology?
Thanks a million! <3

**Comment by Vali-98** [comment]
Hey there, this was actually pointed out to me a while ago that I haven't setup up requirements properly, but I never got around to fixing it. You can simply change the numpy version in the requirements.txt to 1.22 and this should probably fix the issue. I will also quickly push the changed line.

So far I've only tested this repo on two machines, but this was before changing the requirements.txt after another user reported it breaking on linux.

Regarding install, there aren't any other instructions other than whats in the README.md, and since I've only really tested this on personal machines, I can't say much on problems that may occur on other systems.

Sorry for the confusion, feel free to follow up on whether the numpy change doesn't fix it or otherwise close the issue.
